google_maps:
  url: "https://maps.googleapis.com/maps/api/geocode/"
  api_key: AIzaSyDTqtmrydnGQEcjZhsDgCpXN09415u2xQg
postgresql:
  host: localhost
  database: pharmeasy
  username: pharmeasy
  password: password
